#!/bin/sh 

# This is an example script for diskless-booted systems over NFS.
# In order to make the script working properly, you need to adjust
# the parameters below and you also aready need to have booted
# your root environment over NFS, either by an initrd/initramfs
# or by your specific OS NFS-boot method (e.g. see 
# ${path_to_linux_sources}/Documentation/nfsroot.txt).
# Furtheremore, this script expectes your NFS-server to export
# /unionfs/hosts (MUST be read-write) and 
# /unionfs/groups/default (read-only is sufficient).
# You then also MUST have the directory /unionfs/host and
# /unionfs/groups/default with these 
# subdirectories: bin  etc  lib  lib32  root  sbin  usr  var
#
# All of this is only an example, of course, and may be easily changed.
#
# On my systems this script is then executed as the very first init-script,
# thus before any other init script is executed. On debian/ubuntu this
# can be done by copying this script to /etc/init.d/unionfs-fuse and then
# by creating a link /etc/rcS.d/S01a_unionfs-fuse -> ../init.d/unionfs-fuse.
#
# NOTE: It is generally advisable to monitor the very first boot process of 
# a client using a serial cable, SOL (ipmi) or serial netconsole.
#
# LICENSE: new BSD license, see LICENSE file for details.
# Copyright: Bernd Schubert <bernd-schubert@gmx.de>

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/opt/local/bin:/opt/local/sbin

NET="10.68.0.[2-9][^0-9]"
NFS_SERV="10.68.0.1"
NFS_OPT="-orw,hard,intr,bg,timeo=600,nolock"

FUSE_OPT="-o default_permissions -o allow_other -o use_ino -o nonempty -o suid"
UNION_OPT="-o cow"

UPATH="/unionfs"
UBIN="/usr/bin/unionfs-fuse"

IP=`ip addr show |grep $NET | sed -e s'/^.*inet //' |sed -e s'/\/[0-9]* brd.*$//'`

[ -z "$IP" ] && exit 0

if [ "$IP" = "$NFS_SERV" ]; then
	# The nfs server shall not create a union of itself, abort!
	echo "This system is the nfs-server, I won't mount myself!"
	exit 1
fi

# allow more open files, reminder: everything in /etc and /var is opened by 
# ${UPATH} e.g. with fontconfig caching the default of 1024 open file can be 
# too small
ulimit -n 16384

modprobe fuse

# the client specific files
mount -n -t nfs $NFS_OPT ${NFS_SERV}:/${UPATH}/overlay /${UPATH}/overlay

unionmount()
{
	dir=$1

	mount -n --bind /$dir /$UPATH/master/$dir
	host="/${UPATH}/overlay/${dir}=RW"
	common="/$UPATH/master/${dir}=RO"
	$UBIN $FUSE_OPT $UNION_OPT ${host}:${common} /$UPATH/union/$dir
	mount -n --bind /$UPATH/union/$dir /$dir
}

unionmount_ro()
{
	dir=$1

	mount -n --bind /$dir /$UPATH/master/$dir
	host="/${UPATH}/overlay/${dir}=RW"
	common="/$UPATH/master/${dir}=RO"

	$UBIN $FUSE_OPT $UNION_OPT ${host}:${common} /$UPATH/union/$dir
	mount -n --bind /$UPATH/union/$dir /$dir
	mount -o remount,ro /$dir
}

unionmount var
unionmount_ro etc

# Run init
exec /sbin/init "$@"
