#!/bin/sh

set -e

#DEBHELPER#

PKG=pr2-network

case "$1" in
  upgrade|install)
	BASESTATION_IP=`gethostip -d basestation-novpn` || 
	BASESTATION_IP=`gethostip -d basestation` || 
	BASESTATION_IP="10.0.0.1"

	BASESTATION_HOSTNAME=`python -c """
with open('/etc/hosts') as f:
    res = f.read()
    for r in res.split('\n'):
        if '10.68.255.1' in r:
            print r.replace('10.68.255.1', '').strip(' ')
            exit(0)
    print '"basestation_hostname_not_found"'
"""`

	mkdir -p /tmp/pr2-network
	echo ${BASESTATION_IP} > /tmp/pr2-network/BASESTATION_IP
	echo ${BASESTATION_HOSTNAME} > /tmp/pr2-network/BASESTATION_HOSTNAME
    ;;
  
  *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
